image: registry.gitlab.com/christiantragesser/helm-repo:ci

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    LOCAL_TAG: local/helm-repo
    EXT_TAG: $CI_REGISTRY/christiantragesser/helm-repo
    
services:
- name: docker:stable-dind

stages:
  - release

release:
  stage: release
  script:
    - VERSION=$(date +"%s")
    - mkdir /tmp/payload && cd /tmp/payload
    - git clone https://github.com/christianTragesser/docker-poc_app.git
    - git clone https://github.com/christianTragesser/fakos.git
    - helm package ./docker-poc_app/helm/poc-app
    - helm package ./fakos/helm/fakos
    - mv /tmp/payload/*.tgz $CI_PROJECT_DIR/docker/helm/
    - helm repo index $CI_PROJECT_DIR/docker/helm/
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $LOCAL_TAG -f $CI_PROJECT_DIR/docker/Dockerfile $CI_PROJECT_DIR/docker
    - docker tag $LOCAL_TAG ${EXT_TAG}:latest 
    - docker tag ${EXT_TAG}:latest ${EXT_TAG}:rel-${VERSION}
    - docker push ${EXT_TAG}:latest | grep -e "The push refers to" -e latest
    - docker push ${EXT_TAG}:rel-${VERSION} | grep -e "The push refers to" -e latest
  only:
    - master
